"""Verify the Pine sources and generate the compiler-run smoke harness."""

import hashlib
import re
import sys
from pathlib import Path

SCRIPT_PATH = Path(__file__).absolute()
REPO_ROOT = SCRIPT_PATH.parent.parent
CHECKOUT_ROOT = REPO_ROOT.resolve(strict=True)
SCRIPT_RELATIVE_PATH = SCRIPT_PATH.relative_to(REPO_ROOT)
PRODUCTION_PATH = Path("indicators/pe.pine")
VALIDATION_PATH = Path("docs/validation.md")
README_PATH = Path("README.md")
LICENSE_PATH = Path("LICENSE")
HARNESS_PATH = Path("tmp/pe-contract-tests.pine")
START_MARKER = "// @contract pe-ratio:start"
END_MARKER = "// @contract pe-ratio:end"
ANALYST_MODE = "Reported-quarter estimate ×4 (proxy)"
LICENSE_HEADER = (
    "// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 "
    "at https://mozilla.org/MPL/2.0/\n// © golyshevskii\n"
)


def fail(message: str) -> SystemExit:
    return SystemExit(f"ERROR: {message}")


def required_file(relative_path: Path) -> Path:
    try:
        resolved_path = (REPO_ROOT / relative_path).resolve(strict=True)
    except FileNotFoundError:
        raise fail(f"required file is missing: {relative_path}") from None

    try:
        resolved_path.relative_to(CHECKOUT_ROOT)
    except ValueError:
        raise fail(f"required file resolves outside the repository: {relative_path}") from None
    if not resolved_path.is_file():
        raise fail(f"required path is not a file: {relative_path}")
    return resolved_path


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def read_source(relative_path: Path) -> tuple[str, str]:
    content = required_file(relative_path).read_bytes()
    return content.decode("utf-8"), sha256(content)


def extract_contract(source: str) -> str:
    lines = source.splitlines()
    if lines.count(START_MARKER) != 1 or lines.count(END_MARKER) != 1:
        raise fail("production source must contain exactly one pe-ratio contract block")
    start = lines.index(START_MARKER)
    end = lines.index(END_MARKER)
    if end <= start + 1:
        raise fail("pe-ratio contract block is empty or malformed")

    block = "\n".join(lines[start + 1 : end]) + "\n"
    production_call = "pe = peRatio(close, epsTTM)"
    if lines.count(production_call) != 1:
        raise fail("production calculation must call the extracted peRatio contract")
    if any(re.match(r"^\s*pe\s*:=", line) for line in lines[lines.index(production_call) + 1 :]):
        raise fail("production calculation must not reassign pe after the contract call")
    return block


def check_data_contract(source: str) -> None:
    compact = " ".join(source.split())
    required = (
        "not na(price) and price > 0 and not na(eps) and eps > 0 ? price / eps : na",
        "not na(reportedQuarterEstimate) and reportedQuarterEstimate > 0 ? reportedQuarterEstimate * 4 : na",
        'epsTTM = request.financial(syminfo.tickerid, epsId, "TTM", gaps=barmerge.gaps_off, ignore_invalid_symbol=true, currency=syminfo.currency)',
        f'if showFwd and fwdMode == "{ANALYST_MODE}" estQ := request.earnings(syminfo.tickerid, earnings.estimate, gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_off, ignore_invalid_symbol=true, currency=syminfo.currency)',
        "scenarioEPS = growthScenarioEPS(epsTTM, growthPct)",
        "analystEPS = analystProxyEPS(estQ)",
        'fwdEPS = fwdMode == "Growth assumption" ? scenarioEPS : analystEPS',
        "fwdPE = showFwd ? peRatio(close, fwdEPS) : na",
        'plot(fwdPE, "Forward P/E"',
        'table.cell(t, 1, 2, showFwd ? (na(fwdPE) ? "n/a" : str.tostring(fwdPE, "#.##")) : "Off"',
    )
    for statement in required:
        if statement not in compact:
            raise fail(f"production data contract is missing: {statement}")
    if "lookahead=" in compact.split("request.financial", maxsplit=1)[1].split(")", maxsplit=1)[0]:
        raise fail("request.financial must not receive lookahead")
    if compact.count("request.financial(") != 1 or compact.count("request.earnings(") != 1:
        raise fail("production must have exactly one financial and one earnings request")


def render_harness(source: str, source_hash: str) -> str:
    contract = extract_contract(source)
    return f"""{LICENSE_HEADER}
// Generated by scripts/check_pe.py; edit indicators/pe.pine instead.
// Production SHA-256: {source_hash}
//@version=6
indicator("P/E contract smoke")

{contract}
closeEnough(float actual, float expected) =>
    not na(actual) and math.abs(actual - expected) <= math.max(1e-8, 1e-10 * math.abs(expected))

bool ratioFixtures = closeEnough(peRatio(100.0, 5.0), 20.0) and na(peRatio(float(na), 5.0)) and na(peRatio(0.0, 5.0)) and na(peRatio(100.0, float(na))) and na(peRatio(100.0, 0.0)) and na(peRatio(100.0, -5.0)) and closeEnough(peRatio(100.0, 0.000001), 100000000.0)
bool growthFixtures = closeEnough(growthScenarioEPS(5.0, 8.0), 5.4) and closeEnough(peRatio(100.0, growthScenarioEPS(5.0, 8.0)), 100.0 / 5.4) and closeEnough(growthScenarioEPS(5.0, -50.0), 2.5) and closeEnough(growthScenarioEPS(5.0, 300.0), 20.0) and na(growthScenarioEPS(float(na), 8.0)) and na(growthScenarioEPS(0.0, 8.0)) and na(growthScenarioEPS(-5.0, 8.0))
bool analystFixtures = closeEnough(analystProxyEPS(2.5), 10.0) and closeEnough(peRatio(100.0, analystProxyEPS(2.5)), 10.0) and na(analystProxyEPS(float(na))) and na(analystProxyEPS(0.0)) and na(analystProxyEPS(-2.5))
bool smokePass = ratioFixtures and growthFixtures and analystFixtures
if barstate.islast and not smokePass
    runtime.error("peRatio smoke check failed")
plot(smokePass ? 1 : 0, "Smoke result")
"""


def validated_harness_path() -> Path:
    harness_path = REPO_ROOT / HARNESS_PATH
    try:
        harness_path.parent.resolve(strict=False).relative_to(CHECKOUT_ROOT)
    except ValueError:
        raise fail(f"harness directory resolves outside the repository: {harness_path.parent}") from None
    if harness_path.is_symlink():
        raise fail(f"generated harness must not be a symlink: {HARNESS_PATH}")
    return harness_path


def check(check_harness: bool = True) -> tuple[str, str]:
    required_file(SCRIPT_RELATIVE_PATH)
    production, production_hash = read_source(PRODUCTION_PATH)
    if not production.startswith(LICENSE_HEADER):
        raise fail("production MPL-2.0/golyshevskii header changed")
    extract_contract(production)
    check_data_contract(production)
    required_file(README_PATH)
    required_file(VALIDATION_PATH)
    required_file(LICENSE_PATH)

    harness_path = validated_harness_path()
    if check_harness and harness_path.exists():
        expected_harness = render_harness(production, production_hash)
        if harness_path.read_text(encoding="utf-8") != expected_harness:
            raise fail("generated harness is stale: run `make test`")

    print(f"OK production SHA-256 {production_hash}")
    print("OK MPL-2.0 attribution and production-linked contract block")
    print("LOCAL CHECKS PASSED; Pine compilation/runtime were not run")
    return production, production_hash


def generate() -> None:
    production, production_hash = check(check_harness=False)
    harness_path = validated_harness_path()
    harness_path.parent.mkdir(exist_ok=True)
    harness_path.write_text(render_harness(production, production_hash), encoding="utf-8")
    print(f"GENERATED {HARNESS_PATH} from production SHA-256 {production_hash}")
    print("PINE NOT RUN; import the harness into Pine Editor and execute it on a chart")


def main(arguments: list[str]) -> int:
    if arguments == ["check"]:
        check()
        return 0
    if arguments == ["generate"]:
        generate()
        return 0
    raise fail("usage: check_pe.py check|generate")


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
